apiVersion: v1
kind: Service
metadata:
  name: sign-service
  namespace: sign
spec:
  selector:
    app: sign
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000